services:
  back:
    container_name: geo-editor-back
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: build/libs/geo-editor-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    container_name: geo-editor-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d 123456" ]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: geo
    ports:
      - "5433:5432"

volumes:
  postgres-volume: