spring:
  application:
    name: geo-editor

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5433/geo}
    username: root
    password: 123456

  liquibase:
    change-log: classpath:/db/changelog/main-changelog.yaml

mybatis:
  type-handlers-package: ru.vistar.geoeditor.data.mapper.handler
  configuration:
    map-underscore-to-camel-case: true